services:

  master:
    build:
      dockerfile: ./docker/master.Dockerfile
    container_name: node00
    command: bash -c "ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N '' -q && cp /root/.ssh/id_ed25519.pub /shared && exec tail -f /dev/null"
    volumes:
      - shared:/shared

  worker:
    depends_on:
      - master
    build:
      context: ./docker
      dockerfile: worker.Dockerfile
    container_name: node01
    command: bash -c "cat /shared/id_ed25519.pub >> /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys && service ssh restart && exec tail -f /dev/null"
    volumes:
      - shared:/shared

volumes:

  shared:
    name: shared